### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by yukiqt** [shiosyakeyakini-info/miria#223] opened 2023-07-31 19:35 UTC
Could we please have a way to make the app be in English?

I find it slightly difficult to use due to the fact that I do not know Japanese.

**Comment by poppingmoon** [comment] 2023-07-31 20:07
Duplicate of #164

**Comment by yukiqt** [comment] 2023-07-31 21:33
I have no idea what any of that says but ok

**Closed** 2023-07-31 21:59 UTC
